blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/yuis-ice/mva/discussions
    about: Ask questions, share ideas, and discuss mva with the community
  - name: 📖 Documentation
    url: https://github.com/yuis-ice/mva/blob/main/README.md
    about: Read the documentation for setup instructions and usage examples
  - name: 🔧 rclone Documentation
    url: https://rclone.org/docs/
    about: Learn about rclone configuration and troubleshooting
