name: 🚀 Feature Request
description: Suggest an idea for mva
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched for existing feature requests that may be the same as or related to mine
          required: true
        - label: I have read the documentation to understand current capabilities
          required: true
        - label: This feature would benefit the broader mva community
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New command or CLI option
        - Configuration enhancement
        - Archive/compression feature
        - rclone integration improvement
        - Performance optimization
        - Documentation improvement
        - Developer experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like mva to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Other ways this could work..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature in your workflow
      placeholder: "I would use this feature to..."
    validations:
      required: true

  - type: textarea
    id: example-config
    attributes:
      label: Example Configuration/Usage
      description: If applicable, show how this feature might be configured or used
      render: yaml
      placeholder: |
        # Example configuration or command usage
        mva new-feature --option value

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Can't use mva without this
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: "Any additional information that might help..."
